spring:
  application:
    name: app-backend
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/multi-ai-query
#      auto-index-creation: true

server:
  port: 9000

openai:
  # Prefer env var injection
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com
  model: gpt-4o
  connect-timeout: 5s
  read-timeout: 30s
gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com
  model: gemini-2.5-flash
  connect-timeout: 5s
  read-timeout: 30s